
package Study.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://ws.java.main/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "helloService", targetNamespace = "http://ws.java.main/", className = "org.test.HelloService_Type")
    @ResponseWrapper(localName = "helloServiceResponse", targetNamespace = "http://ws.java.main/", className = "org.test.HelloServiceResponse")
    @Action(input = "http://ws.java.main/HelloService/helloServiceRequest", output = "http://ws.java.main/HelloService/helloServiceResponse")
    public void helloService();

    /**
     * 
     * @return
     *     returns org.test.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.java.main/", className = "org.test.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.java.main/", className = "org.test.GetUserResponse")
    @Action(input = "http://ws.java.main/HelloService/getUserRequest", output = "http://ws.java.main/HelloService/getUserResponse")
    public User getUser();

}
